Repository Hdemaceo/ideabox-boilerplate, pull requests merged in 2020-07, with the labels that each got.

#2 Feauture/om css styling folder
  css/reset.css
  css/styles.css
Labels: enhancement

#3 Feature/km html setup
  index.html
Labels: enhancement

#5 Dh desktop layout
  css/styles.css
Labels: enhancement

#6 Feature/add styling to to desktop layout
  css/styles.css
Labels: enhancement

#7 Dh styles adjustments
  css/styles.css
  index.html
Labels: enhancement

#9 Km javascript architecture
  index.html
  src/idea.js
  src/main.js
Labels: bug, enhancement

#10 Dh javascript architecture
  css/styles.css
  index.html
  src/idea.js
  src/main.js
Labels: enhancement

#11 Km adding ideas
  css/styles.css
  src/idea.js
  src/main.js
Labels: bug, enhancement

#12 Dh favoriting deleting ideas
  src/idea.js
  src/main.js
Labels: enhancement

#14 Dh local storage
  src/idea.js
  src/main.js
Labels: enhancement

#15 Om local storage
  src/idea.js
  src/main.js
Labels: bug, enhancement, help wanted

#16 Km local storage and filtering
  README.md
  src/idea.js
  src/main.js
Labels: enhancement

#18 Km refactoring responsive layout
  css/styles.css
  index.html
  src/idea.js
  src/main.js
Labels: enhancement

#19 Om add functionality to burger button
  css/styles.css
  index.html
  src/main.js
Labels: help wanted

#20 Km readme
  .DS_Store
  README.md
  assets/APPLICATION-Desktop.png
  assets/COMP-Desktop.png
  assets/COMP-mobile.png
  assets/Desktop-journey.gif
  assets/Mobile-Journey.gif
  css/styles.css
  index.html
  src/main.js
  styles.css
Labels: enhancement
